apiVersion: v1
kind: Service
metadata:
  name: {{ include "airs-cp.fullname" . }}-gateway
  labels:
    {{- include "airs-cp.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "airs-cp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
---
{{- if .Values.dashboard.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "airs-cp.fullname" . }}-dashboard
  labels:
    {{- include "airs-cp.labels" . | nindent 4 }}
    app.kubernetes.io/component: dashboard
spec:
  type: {{ .Values.dashboard.service.type }}
  ports:
    - port: {{ .Values.dashboard.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "airs-cp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: dashboard
{{- end }}
